Repository hashicorp/terraform-provider-ad, pull requests merged in 2021-01, with the labels that each got.

#66 Add proto to kerb transporter
  ad/config.go
Labels: size/XS

#69 Update descriptions for user and group datasources.
  ad/data_source_ad_group.go
  ad/data_source_ad_group_test.go
  ad/data_source_ad_user.go
  ad/data_source_ad_user_test.go
  docs/data-sources/group.md
  docs/data-sources/user.md
Labels: size/S

#63 Issue58 - Add extra attributes to resource user
  ad/data_source_ad_user.go
  ad/internal/winrmhelper/winrm_user.go
  ad/resource_ad_user.go
  docs/data-sources/user.md
  docs/resources/user.md
  examples/data-sources/ad_user/data-source.tf
  examples/resources/ad_user/resource.tf
Labels: size/XL

#64 Allow dependabot to check go dependencies
  .github/dependabot.yml
Labels: size/XS

#73 support for custom user attributes
  ad/data_source_ad_user.go
  ad/internal/winrmhelper/winrm_helper.go
  ad/internal/winrmhelper/winrm_user.go
  ad/resource_ad_user.go
  ad/resource_ad_user_test.go
  docs/resources/user.md
  examples/resources/ad_user/resource.tf
Labels: size/XL

#76 Export SID for security principals
  ad/data_source_ad_computer.go
  ad/data_source_ad_group.go
  ad/data_source_ad_user.go
  ad/internal/winrmhelper/winrm_computer.go
  ad/internal/winrmhelper/winrm_group.go
  ad/internal/winrmhelper/winrm_helper.go
  ad/internal/winrmhelper/winrm_user.go
  ad/resource_ad_computer.go
  ad/resource_ad_group.go
  ad/resource_ad_user.go
  docs/data-sources/computer.md
  docs/data-sources/group.md
  docs/data-sources/user.md
  docs/resources/computer.md
  docs/resources/group.md
  docs/resources/user.md
Labels: size/S
