Repository hashicorp/terraform-provider-ad, pull requests merged in 2021-06, with the labels that each got.

#114 Migrate most GitHub HashiBot behaviors to GitHub Actions
  .github/labeler-issue-triage.yml
  .github/workflows/issue-comment-created.yaml
  .github/workflows/issue-opened.yaml
  .github/workflows/lock.yaml
  .hashibot.hcl
Labels: size/M

#117 Double hop authentication
  ad/config.go
  ad/data_source_ad_computer.go
  ad/data_source_ad_gpo.go
  ad/data_source_ad_group.go
  ad/data_source_ad_ou.go
  ad/data_source_ad_user.go
  ad/internal/config/config.go
  ad/internal/winrmhelper/powershell_command.go
  ad/internal/winrmhelper/winrm_computer.go
  ad/internal/winrmhelper/winrm_gplink.go
  ad/internal/winrmhelper/winrm_gpo.go
  ad/internal/winrmhelper/winrm_group.go
  ad/internal/winrmhelper/winrm_group_membership.go
  ad/internal/winrmhelper/winrm_helper.go
  ad/internal/winrmhelper/winrm_ou.go
  ad/internal/winrmhelper/winrm_sec.go
  ad/internal/winrmhelper/winrm_user.go
  ad/provider.go
  ad/resource_ad_computer.go
  ad/resource_ad_computer_test.go
  ad/resource_ad_gplink.go
  ad/resource_ad_gplink_test.go
  ad/resource_ad_gpo.go
  ad/resource_ad_gpo_security.go
  ad/resource_ad_gpo_security_test.go
  ad/resource_ad_gpo_test.go
  ad/resource_ad_group.go
  ad/resource_ad_group_membership.go
  ad/resource_ad_group_membership_test.go
  ad/resource_ad_group_test.go
  ad/resource_ad_ou.go
  ad/resource_ad_ou_test.go
  ad/resource_ad_user.go
  ad/resource_ad_user_test.go
  docs/data-sources/computer.md
  docs/data-sources/gpo.md
  docs/data-sources/group.md
  docs/data-sources/ou.md
  docs/data-sources/user.md
  docs/index.md
  docs/resources/computer.md
  docs/resources/gplink.md
  docs/resources/gpo.md
  docs/resources/gpo_security.md
  docs/resources/group.md
  docs/resources/group_membership.md
  docs/resources/ou.md
  docs/resources/user.md
  templates/index.md.tmpl
Labels: size/XXL

#122 pre-release changelog update
  CHANGELOG.md
Labels: size/XS
