Repository hashicorp/terraform-provider-ad, pull requests merged in 2022-04, with the labels that each got.

#133 [Issue 123] Add distinguished_name attribute to user and group data sources and resources
  ad/data_source_ad_group.go
  ad/data_source_ad_user.go
  ad/resource_ad_group.go
  ad/resource_ad_user.go
Labels: size/XS

#136 Minor Change - New Functionality - Ability to Specify a Domain Controller
  ad/internal/config/config.go
  ad/internal/winrmhelper/winrm_computer.go
  ad/internal/winrmhelper/winrm_gplink.go
  ad/internal/winrmhelper/winrm_gpo.go
  ad/internal/winrmhelper/winrm_group.go
  ad/internal/winrmhelper/winrm_group_membership.go
  ad/internal/winrmhelper/winrm_helper.go
  ad/internal/winrmhelper/winrm_ou.go
  ad/internal/winrmhelper/winrm_user.go
  ad/provider.go
Labels: size/M

#138 Implement support for Kerberos keytab files
  ad/internal/config/config.go
  ad/provider.go
Labels: size/S

#143 Migrate Provider Releases from TeamCity to GitHub Actions
  .github/workflows/release.yml
  .goreleaser.yml
  terraform-registry-manifest.json
Labels: size/L
